version: '2.1'

services:
  core:
    build: services/core-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  event:
    build: services/event-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  stat:
    build: services/stat-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  engine:
    build: services/engine-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
